apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dados-dinamicos
  namespace: curso-storage
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: curso-ebs-gp3
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: arquivo-dinamico
  namespace: curso-storage
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: arquivo
      image: busybox:1.37.0
      command: [sh, -c, "sleep 86400"]
      resources:
        requests: {cpu: 10m, memory: 16Mi}
        limits: {cpu: 100m, memory: 64Mi}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ALL]
      volumeMounts:
        - name: dados
          mountPath: /dados
  volumes:
    - name: dados
      persistentVolumeClaim:
        claimName: dados-dinamicos
