apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: curso-ebs-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: gp3
  encrypted: "true"
  kmsKeyId: alias/aws/ebs
  csi.storage.k8s.io/fstype: ext4
  tagSpecification_1: Curso=kubernetes
