apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agenda
  namespace: curso-scheduling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agenda
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
